name: EnergyOrigin

env:
  app-name: app-ett
  BASE_BRANCH: ${{ github.ref_name }}
  is-main-branch: ${{ github.event.workflow_run.head_branch == 'refs/heads/main' }}
  is-pull-request: ${{ github.event.workflow_run.event  == 'pull_request' }}
  is-push: ${{ github.event.workflow_run.event  == 'push' }}
  NODE_OPTIONS: --max-old-space-size=6144
  node-version: 14.x
  NX_MAX_PARALLEL: 2

  # Nx Cloud
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_RUN_GROUP: ${{ github.run_id }}


on:
  workflow_run:
    # Change back
    #workflows: ['GreenForce Frontend CI']
    workflows: ['Test Workflow']
    types: [completed]

jobs:
  test:
    name: "test"
    env: 
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      EVENT_NAME: ${{github.event_name}}
      B_BRANCH: ${{github.event.workflow_run.pull_requests[0].base.ref}}
      H_BRANCH: ${{github.event.workflow_run.pull_requests[0].head.ref}}
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "$GITHUB_CONTEXT"
      - name: "B_BRANCH"
        run: echo "$B_BRANCH"
      - name: "H_BRANCH"
        run: echo "$H_BRANCH"
      

  affected:
    name: Is affected?
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    outputs:
      is-affected: "true"

    steps:
      - run: echo "test"
  app:
    name: Build app
    if: ${{ needs.affected.outputs.is-affected == 'true' }}
    needs: affected
    runs-on: ubuntu-latest

    steps:
      - run: echo "test"

  container-pr:
    name: 'PR: Host container'
    if: ${{ github.event.workflow_run.event  == 'pull_request' }}
    needs: app
    runs-on: ubuntu-latest
    env:
      host-image-tag: ${{ format('pr-{0}', github.event.pull_request.number) }}
    steps:
      - run: echo "test"

  container_merge:
    name: 'Merge: Host container'
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.event  == 'push' }}
    needs: app
    outputs:
      release_tag: "v0.0.1"
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"

  update_base_env:
    name: Update Base Environment
    runs-on: ubuntu-latest
    needs:
      - container_merge
    env:
      SERVICE_NAME: eo-frontend

      # BASE_ENV_REPO: 'Energinet-DataHub/eo-base-environment'
      BASE_ENV_REPO: 'RasmusGodske/eo-base-environment'
      BASE_ENV_REPO_BRANCH: 'development'
      HELM_CHART_PATH: 'yggdrasil/applications/eo/eo-frontend/eo-frontend.yaml'
      JOB_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

    steps:
      - run: echo "test"
